# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rtbot}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Daniels"]
  s.date = %q{2010-07-26}
  s.default_executable = %q{rtbot}
  s.description = %q{Provides an rtbot script which you can configure to make a very simply Twitter retweeting bot.}
  s.email = %q{john@semantici.st}
  s.executables = ["rtbot"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rtbot",
     "config.yml.example",
     "lib/rtbot.rb",
     "rtbot.gemspec",
     "test/helper.rb",
     "test/test_rtbot.rb"
  ]
  s.homepage = %q{http://github.com/johnd/rtbot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A simple Twitter RTing bot.}
  s.test_files = [
    "test/helper.rb",
     "test/test_rtbot.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twitter>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2"])
    else
      s.add_dependency(%q<twitter>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2"])
    end
  else
    s.add_dependency(%q<twitter>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2"])
  end
end

